### PR TITLE
fix roles & authorize roles for CategoriesController

### PR DESCRIPTION
**Pull request by JustMike13**
- Now the app creates the 4 user roles on every run, if they are not created already;
- Added a role authorization for the Categories controller, only the admin can create, edit or delete a category

### CODE REVIEW

**Comment by dragosconst** [comment]
Looks good to me, will test it locally later.

**Comment by dragosconst** [comment]
Tested it locally, seems there is a problem with the naming of namespaces in the new Models & Controllers.

**Comment by eduardvintila** [comment]
Tested it, too. Seems to be working fine now.

**Comment by dragosconst** [comment]
Ran some local tests, everything is working good. Will merge it into master.

**Pull request merged**
