### PR TITLE
Add multiple photos option for Posts and Products

### PR DESCRIPTION
**Pull request by eduardvintila**
Worked on this task with @dragosconst

For now, we can upload a maximum of 5 photos per product/post.
There may be some issues when navigating the pictures of a product. Also the layout of the upload buttons is not great at the moment.

### CODE REVIEW

**Comment by dragosconst** [comment]
The bug seems to have finally been fixed, but I found another weird bug regarding the number of photos in a Post. For some reason, if I create a Post with, say, 3 photos, I can't edit it to add a 4th photo. It seems to be limited by the amount of photos the Post had when it was initially created.

**Comment by dragosconst** [comment]
It also seems to be fairly arbitrary? Sometimes I can increase the number of photos and sometimes it won't work (on any user). It's possible to have to do with the order of upload buttons? Not sure.

**Comment by dragosconst** [comment]
Looks good now, the bug seems to have been fixed. Probably ready for merging.

**Comment by JustMike13** [comment]
It looks good to me, no problems found.

**Pull request merged**
