### PR TITLE
Posts on Products + basic star rating system for reviews

### PR DESCRIPTION
**Pull request by eduardvintila**

### CODE REVIEW

**Comment by JustMike13** [comment]
New and Edit methods on PostController do not update the product's rating but that does not cause any issues, for now. The branch can be merged into main.

**Comment by eduardvintila** [comment]
> New and Edit methods on PostController do not update the product's rating but that does not cause any issues, for now. The branch can be merged into main.

Okay, I will try to fix this now.

**Comment by dragosconst** [comment]
Tested locally, works fine (except of course it doesn't update the product's rating yet), but I had to delete all my rows from the Posts table. It threw an exception on the product's primary key for some reason. Not really a problem, but just a heads up if anyone else had stuff in their Posts table.

**Comment by dragosconst** [comment]
Tested locally, no bugs detected. Probably ready for merging.

**Pull request merged**
