### PR TITLE
design view Cart 

### PR DESCRIPTION
**Pull request by JustMike13**

### CODE REVIEW

**Comment by eduardvintila** [comment]
Works good. The new design is nice.

**Comment by dragosconst** [comment]
Looks really nice, but there seems to be a design bug on the Show View for individual Orders: 
image

**Comment by JustMike13** [comment]
image
I can't find a way top reproduce the bug. Could you be more specific on how you found it?

**Comment by dragosconst** [comment]
It seems to be firefox-specific, I ran the app in Edge and it looked fine. Weird, but I'm not sure if we should consider it a bug.

**Comment by dragosconst** [comment]
Looks fine now.

**Pull request merged**
